// // SPDX-License-Identifier: MIT
// // Transitively pulls in `lib/semaphore`'s `ISemaphore.sol`, pinned to exactly `0.8.23` — see
// // `foundry.toml`.
// pragma solidity 0.8.23;

// import {Test} from "forge-std/Test.sol";
// import {Semaphore} from "@semaphore-protocol/contracts/Semaphore.sol";
// import {SemaphoreVerifier} from "@semaphore-protocol/contracts/base/SemaphoreVerifier.sol";
// import {ISemaphoreVerifier} from "@semaphore-protocol/contracts/interfaces/ISemaphoreVerifier.sol";
// import {ISemaphore} from "@semaphore-protocol/contracts/interfaces/ISemaphore.sol";
// import {TARRecoveryExecutorV2} from "../../src/TARRecoveryExecutorV2.sol";
// import {ITARRecoveryV2} from "../../src/interfaces/ITARRecoveryV2.sol";
// import {MockERC7579Account} from "../mocks/MockERC7579Account.sol";
// import {MockRotatableValidator} from "../mocks/MockRotatableValidator.sol";

// /// @notice Milestone D: cross-checks JS-generated real Groth16 Semaphore proofs (fixture at
// /// `test/fixtures/semaphore_proof_vector.json`, generated by `script/js/generate-fixture.mjs` —
// /// see docs/v2/context_mD_v2.md) against the real `Semaphore.sol`/`SemaphoreVerifier.sol`, not
// /// `MockSemaphore`. Goal: catch any JS/Solidity `SemaphoreProof` encoding mismatch before Kernel
// /// integration (Milestone F) — if a test here fails unexpectedly, suspect the fixture/encoding
// /// first, not `challengeRecovery`'s logic (already covered against `MockSemaphore` in
// /// `TARRecoveryExecutorV2Challenge.t.sol`).
// ///
// /// The fixture's "invalid" proof is deliberately *not* built from an identity genuinely absent
// /// from the group — the Semaphore circuit computes `merkleTreeRoot` as an output derived from the
// /// witness, so a non-member's proof would carry a different root entirely and get rejected by
// /// `Semaphore__MerkleTreeRootIsNotPartOfTheGroup` before ever reaching the Groth16 verifier, not
// /// by `verifyProof` returning `false`. Since `challengeRecovery` only raises
// /// `InvalidWatchTowerProof` on that latter path, the fixture instead reuses the valid proof's
// /// root/nullifier/message/scope (passes every structural check) with corrupted `points`, so only
// /// the final pairing check fails. See `script/js/generate-fixture.mjs` for the full rationale.
// contract SemaphoreProofVectorTest is Test {
//     uint256 constant LOCK_VALUE = 1 ether;
//     uint256 constant LOCK_TIME = 3 days;

//     Semaphore semaphore;
//     TARRecoveryExecutorV2 executor;
//     MockERC7579Account account;

//     address broadcaster = address(0xB0AD);
//     uint256 newPubKeyX = uint256(keccak256("newPubKeyX"));
//     uint256 newPubKeyY = uint256(keccak256("newPubKeyY"));

//     function setUp() external {
//         semaphore = new Semaphore(ISemaphoreVerifier(address(new SemaphoreVerifier())));
//         executor = new TARRecoveryExecutorV2(address(new MockRotatableValidator()), address(semaphore));

//         // The fixture's proof `scope` is `uint256(uint160(testAccountAddress))` — a fixed value
//         // baked in at JS-generation time. `MockERC7579Account`'s address is otherwise whatever
//         // CREATE assigns it, so its immutable `owner` is preserved but placed at the exact
//         // address the fixture expects: no separate deploy-then-etch mismatch, since `owner` is
//         // inlined into the runtime bytecode itself, not stored via SSTORE.
//         string memory json = vm.readFile("test/fixtures/semaphore_proof_vector.json");
//         address fixedAddress = vm.parseJsonAddress(json, ".testAccountAddress");
//         MockERC7579Account template = new MockERC7579Account(address(0xBEEF));
//         vm.etch(fixedAddress, address(template).code);
//         account = MockERC7579Account(payable(fixedAddress));

//         account.installModule(address(executor), abi.encode(LOCK_VALUE, LOCK_TIME));
//         vm.deal(broadcaster, 100 ether);
//     }

//     function _reconstructGroup(string memory json) internal {
//         uint256[] memory members = vm.parseJsonUintArray(json, ".group.members");
//         vm.prank(address(account));
//         executor.regenerateWatchTowerGroup(members);
//     }

//     function _requestAndReveal(bytes32 salt) internal {
//         bytes32 commitment = keccak256(abi.encodePacked(address(account), broadcaster, newPubKeyX, newPubKeyY, salt));
//         executor.requestRecovery(commitment);
//         vm.roll(block.number + 1);
//         vm.prank(broadcaster);
//         executor.revealRecovery{value: LOCK_VALUE}(address(account), broadcaster, newPubKeyX, newPubKeyY, salt);
//     }

//     function _parseProof(string memory json, string memory key)
//         internal
//         pure
//         returns (ISemaphore.SemaphoreProof memory proof)
//     {
//         proof.merkleTreeDepth = vm.parseJsonUint(json, string.concat(key, ".merkleTreeDepth"));
//         proof.merkleTreeRoot = vm.parseJsonUint(json, string.concat(key, ".merkleTreeRoot"));
//         proof.nullifier = vm.parseJsonUint(json, string.concat(key, ".nullifier"));
//         proof.message = vm.parseJsonUint(json, string.concat(key, ".message"));
//         proof.scope = vm.parseJsonUint(json, string.concat(key, ".scope"));

//         uint256[] memory points = vm.parseJsonUintArray(json, string.concat(key, ".points"));
//         for (uint256 i = 0; i < 8; i++) {
//             proof.points[i] = points[i];
//         }
//     }

//     function test_validProof_acceptedByRealVerifier() external {
//         string memory json = vm.readFile("test/fixtures/semaphore_proof_vector.json");
//         _reconstructGroup(json);
//         _requestAndReveal(bytes32(uint256(1)));

//         executor.challengeRecovery(address(account), _parseProof(json, ".valid"));

//         (,,,,, TARRecoveryExecutorV2.RecoveryStatus status) = executor.recoveries(address(account));
//         assertEq(uint8(status), uint8(TARRecoveryExecutorV2.RecoveryStatus.Rejected));
//         assertEq(address(account).balance, LOCK_VALUE);
//     }

//     function test_invalidProof_rejectedWithInvalidWatchTowerProof() external {
//         string memory json = vm.readFile("test/fixtures/semaphore_proof_vector.json");
//         _reconstructGroup(json);
//         _requestAndReveal(bytes32(uint256(1)));

//         vm.expectRevert(ITARRecoveryV2.InvalidWatchTowerProof.selector);
//         executor.challengeRecovery(address(account), _parseProof(json, ".invalid"));

//         (,,,,, TARRecoveryExecutorV2.RecoveryStatus status) = executor.recoveries(address(account));
//         assertEq(uint8(status), uint8(TARRecoveryExecutorV2.RecoveryStatus.Revealed));
//     }
// }
